"""Test the report preview HTML renderer.

The preview is generated by rendering the docx and converting it to HTML
via mammoth — the docx is the single source of truth, the preview is its
HTML projection. These tests verify that the preview mirrors the docx
content end-to-end: title page, scope, executive summary, detailed
findings (with Tenable plugin references), conclusion, and that it
reflects draft overrides (impact, recommendation, severity_override,
exec_summary, overall_rating).
"""

from __future__ import annotations

import re


# Minimal sample ctx matching the shape build_report_context produces.
def _make_ctx() -> dict:
    return {
        "engagement": {
            "code": "E1",
            "name": "Acme Webapp Pentest",
            "client": "Acme Corp",
            "type": "webapp",
            "status": "active",
            "methodology": "OWASP-WSTG",
            "start_date": "2025-10-02",
            "end_date": "2025-10-15",
            "report_due_date": "",
        },
        "generated_at": "2025-10-15T12:00:00+00:00",
        "summary": {
            "total_findings": 2,
            "by_severity": {"high": 1, "medium": 1},
            "unique_vulnerabilities": 2,
            "assets_affected": 2,
        },
        "findings": [
            {
                "finding_id": "fid-1",
                "vuln_id": "vid-1",
                "title": "SQL Injection in login form",
                "cve_id": "CVE-2024-1234",
                "cwe_id": "CWE-89",
                "severity": "high",
                "cvss_score": 8.6,
                "asset_value": "10.0.0.10",
                "asset_type": "host",
                "port": 443,
                "protocol": "tcp",
                "status": "open",
                "evidence": "",
                "description": "The login form is vulnerable to SQL injection.",
                "impact": "An attacker could bypass authentication.",
                "recommendation": "Use parameterised queries.",
                "linked_asset_count": 1,
                "source_plugin": "nessus",
                "source_plugin_id": "12345",
                "references": [],
                "issues_text": (
                    "SQL Injection in login form (CVE-2024-1234)\n\n"
                    "The login form is vulnerable to SQL injection.\n\n"
                    "Tenable Plugin ID: 12345\n"
                    "Tenable Plugin: nessus\n"
                    "Tenable Reference: https://www.tenable.com/plugins/index.php?id=12345\n"
                    "CWE: CWE-89"
                ),
            },
            {
                "finding_id": "fid-2",
                "vuln_id": "vid-2",
                "title": "Missing security header",
                "cve_id": None,
                "cwe_id": "CWE-16",
                "severity": "medium",
                "cvss_score": 5.3,
                "asset_value": "10.0.0.11",
                "asset_type": "host",
                "port": 443,
                "protocol": "tcp",
                "status": "open",
                "evidence": "",
                "description": "CSP header missing.",
                "impact": "Increased XSS exposure.",
                "recommendation": "Add Content-Security-Policy.",
                "linked_asset_count": 1,
                "source_plugin": "nessus",
                "source_plugin_id": "98765",
                "references": [],
                "issues_text": (
                    "Missing security header\n\n"
                    "CSP header missing.\n\n"
                    "Tenable Plugin ID: 98765\n"
                    "Tenable Plugin: nessus\n"
                    "Tenable Reference: https://www.tenable.com/plugins/index.php?id=98765\n"
                    "CWE: CWE-16"
                ),
            },
        ],
        "detailed_findings": [
            {
                "vuln_id": "vid-1",
                "severity": "high",
                "affected_assets": ["10.0.0.10"],
                "port": 443,
                "protocol": "tcp",
                "issues_title": "SQL Injection in login form",
                "cve_id": "CVE-2024-1234",
                "impact": "An attacker could bypass authentication.",
                "recommendation": "Use parameterised queries.",
                "action_urgency": "Immediate",
                "description": "The login form is vulnerable to SQL injection.",
                "source_plugin": "nessus",
                "source_plugin_id": "12345",
                "references": [],
                "issues_text": (
                    "SQL Injection in login form (CVE-2024-1234)\n\n"
                    "The login form is vulnerable to SQL injection.\n\n"
                    "Tenable Plugin ID: 12345\n"
                    "Tenable Plugin: nessus\n"
                    "Tenable Reference: https://www.tenable.com/plugins/index.php?id=12345\n"
                    "CWE: CWE-89"
                ),
            },
            {
                "vuln_id": "vid-2",
                "severity": "medium",
                "affected_assets": ["10.0.0.11"],
                "port": 443,
                "protocol": "tcp",
                "issues_title": "Missing security header",
                "cve_id": None,
                "impact": "Increased XSS exposure.",
                "recommendation": "Add Content-Security-Policy.",
                "action_urgency": "Urgent",
                "description": "CSP header missing.",
                "source_plugin": "nessus",
                "source_plugin_id": "98765",
                "references": [],
                "issues_text": (
                    "Missing security header\n\n"
                    "CSP header missing.\n\n"
                    "Tenable Plugin ID: 98765\n"
                    "Tenable Plugin: nessus\n"
                    "Tenable Reference: https://www.tenable.com/plugins/index.php?id=98765\n"
                    "CWE: CWE-16"
                ),
            },
        ],
    }


def test_render_preview_html_contains_all_required_sections():
    from app.services.reporting.render import render_preview_html
    ctx = _make_ctx()
    html = render_preview_html(ctx)
    assert html.startswith("<!DOCTYPE html>")
    assert "<html" in html
    assert "</html>" in html
    # Title page (For/Type/From/Date come from the DMC template, wrapped
    # by mammoth as <p>Label    : </p> in the title-page table).
    assert "Acme Corp" in html
    assert "Web Application Penetration Testing" in html
    assert re.search(r"<p>For\s*:", html) is not None
    assert re.search(r"<p>Type\s*:", html) is not None
    assert re.search(r"<p>From\s*:", html) is not None
    assert re.search(r"<p>Date\s*:", html) is not None
    # Scope table — heading text comes straight from the DMC template
    # ("Scope of work and Timeline", lowercase w).
    assert "Scope of work" in html
    assert "10.0.0.10" in html
    assert "10.0.0.11" in html
    assert "TS Office" in html
    # Disclaimer
    assert "DISCLAIMER" in html
    # Executive summary — section headings come from the DMC template.
    assert "Executive Summary" in html
    assert "Objective" in html
    assert "Methodology" in html
    assert "Severity level" in html
    assert "Action urgency" in html
    assert "Summary of key findings" in html
    assert "Overall security rating" in html
    # Detailed findings with Tenable plugin references
    assert "DETAILED FINDINGS" in html
    assert "Tenable Plugin ID: 12345" in html
    assert "Tenable Reference" in html
    assert "CWE-89" in html
    # Conclusion
    assert "CONCLUSION" in html


def test_render_preview_html_inlines_css_and_no_external_assets():
    from app.services.reporting.render import render_preview_html
    html = render_preview_html(_make_ctx())
    # Inline CSS (a <style> block, not a <link>)
    assert "<style>" in html
    # No external script or stylesheet links
    assert "<link" not in html
    assert "<script" not in html


def test_render_preview_html_risk_severity_colors_present():
    from app.services.reporting.render import render_preview_html
    html = render_preview_html(_make_ctx())
    # severity CSS classes
    for cls in ("sev-critical", "sev-high", "sev-medium", "sev-low", "sev-info"):
        assert f".{cls}" in html


def test_render_preview_html_draft_overrides_applied():
    """After _apply_draft, the preview should reflect the analyst's edits."""
    from app.services.reporting.render import _apply_draft, render_preview_html
    ctx = _make_ctx()
    draft = {
        "exec_summary": "Custom narrative for the executive team.",
        "overall_rating": "Low",
        "finding_overrides": {
            "fid-1": {
                "severity_override": "critical",
                "impact": "OVERRIDDEN IMPACT TEXT",
                "recommendation": "OVERRIDDEN RECOMMENDATION TEXT",
            },
        },
    }
    _apply_draft(ctx, draft)
    html = render_preview_html(ctx)
    # exec summary narrative
    assert "Custom narrative for the executive team." in html
    # overall rating overridden
    assert "Low" in html
    # finding-level overrides propagated to detailed_findings
    assert "OVERRIDDEN IMPACT TEXT" in html
    assert "OVERRIDDEN RECOMMENDATION TEXT" in html
    # severity override flows to "Critical" label
    assert "Critical" in html


def test_render_preview_html_groups_by_severity():
    from app.services.reporting.render import render_preview_html
    html = render_preview_html(_make_ctx())
    # high (1.2) and medium (1.3) sections should be present
    assert "1.2 High" in html
    assert "1.3 Medium" in html
    # critical/empty sections should be absent (no findings of those severities)
    assert "1.1 Critical" not in html


def test_render_preview_html_includes_scope_assets_for_each_finding():
    from app.services.reporting.render import render_preview_html
    html = render_preview_html(_make_ctx())
    # Both unique assets from findings should appear in the scope table
    # (the docx heading is "Scope of work and Timeline").
    scope_match = re.search(
        r"Scope of work.*?</table>", html, re.DOTALL,
    )
    assert scope_match is not None
    scope = scope_match.group(0)
    assert "10.0.0.10" in scope
    assert "10.0.0.11" in scope


def test_render_preview_html_self_contained_no_signature():
    """The preview must NOT include a cryptographic signature footer or
    custom XML part. It's only ever embedded on the signed docx."""
    from app.services.reporting.render import render_preview_html
    html = render_preview_html(_make_ctx())
    assert "vapt-signature" not in html
    assert "signed by" not in html.lower()
    assert "SHA256" not in html  # no signature hash


def test_render_preview_html_tags_editable_regions():
    """The preview must tag the editable regions so the editor can map
    DOM changes back to the structured draft fields. The narrative is
    wrapped in a <div data-field="exec_summary">; each finding's impact
    and recommendation <td> gets a data-field + data-finding-id."""
    from app.services.reporting.render import _apply_draft, render_preview_html
    # No narrative in the fixture → no exec_summary wrapper
    html0 = render_preview_html(_make_ctx())
    assert 'data-field="exec_summary"' not in html0

    ctx = _make_ctx()
    _apply_draft(ctx, {
        "exec_summary": "My override narrative.\n\nSecond paragraph.",
    })
    html = render_preview_html(ctx)
    assert 'data-field="exec_summary"' in html
    m = re.search(
        r'data-field="exec_summary"[^>]*>(.*?)<h1[^>]*><a[^>]*></a><strong>DETAILED FINDINGS</strong></h1>',
        html, re.DOTALL,
    )
    assert m is not None
    assert "My override narrative." in m.group(1)
    assert "Second paragraph." in m.group(1)

    # Impact and recommendation cells tagged per finding (one per vuln in detailed_findings)
    for fid in ("fid-1", "fid-2"):
        assert f'data-field="finding.impact" data-finding-id="{fid}"' in html
        assert f'data-field="finding.recommendation" data-finding-id="{fid}"' in html


def test_render_preview_html_replaces_dmc_template_literals():
    """The DMC template hardcodes 'Data Management Center', 'DMC', and the
    old test date in prose paragraphs. After rendering with a new
    engagement these must be replaced; the disclaimer brand reference
    and CVE references must NOT be touched."""
    from app.services.reporting.render import render_preview_html
    ctx = _make_ctx()  # client='Acme Corp'
    # Use a different start_date so the new formatted date is clearly
    # distinct from the template's hardcoded "2nd October, 2025".
    ctx["engagement"]["start_date"] = "2025-11-05"
    html = render_preview_html(ctx)

    # Old DMC literals must be gone from the rendered report
    assert "Data Management Center" not in html

    # The template's hardcoded test date is gone (replaced with the new one)
    assert "2nd October, 2025" not in html

    # New engagement's client and formatted start date are present
    assert "Acme Corp" in html
    assert "5th November, 2025" in html

    # The DMC abbreviation in prose is replaced
    # (the template has "DMC's penetration testing", "DMC should also ensure",
    #  and "advisable for DMC to refer" — all should be replaced with "Acme Corp")
    assert "DMC's penetration" not in html
    assert "DMC should also" not in html
    assert "for DMC to refer" not in html

    # The disclaimer is preserved verbatim (brand reference, not engagement-specific)
    assert "This publication has been carefully prepared" in html
    assert "Technovage Solution" in html  # the disclaimer keeps the brand

    # CVE references in finding details are NOT replaced (they live in
    # table cells which are owned by _fill_*, and even in prose the
    # replacement would no-op on CVE refs).
    assert "CVE-2024-1234" in html


def test_replace_template_literals_preserves_paragraph_formatting():
    """The replacement must preserve the paragraph's character formatting
    (bold, etc.) by writing into the first run, not by deleting all
    runs and re-adding."""
    from docx import Document

    from app.services.reporting.render import _replace_template_literals
    from app.services.reporting.render import _resolve_template_path
    template_path = _resolve_template_path()
    assert template_path, "DMC template must be available for this test"
    doc = Document(template_path)
    ctx = _make_ctx()

    # Capture a paragraph's first-run style before replacement
    target = None
    for p in doc.paragraphs:
        if "Data Management Center" in p.text:
            target = p
            break
    assert target is not None
    first_run = target.runs[0]
    bold_before = first_run.bold
    font_size_before = first_run.font.size

    _replace_template_literals(doc, ctx)

    # Same paragraph now has the new client name, not the DMC literal
    assert "Data Management Center" not in target.text
    assert "Acme Corp" in target.text
    # The first run's formatting is preserved
    assert target.runs[0].bold == bold_before
    assert target.runs[0].font.size == font_size_before


def test_replace_template_literals_skips_disclaimer():
    """The disclaimer paragraph must NOT be touched — it contains the
    authoring-house brand reference and is a legal statement."""
    from docx import Document

    from app.services.reporting.render import _replace_template_literals
    from app.services.reporting.render import _resolve_template_path
    template_path = _resolve_template_path()
    assert template_path, "DMC template must be available for this test"
    doc = Document(template_path)
    _replace_template_literals(doc, _make_ctx())

    disclaimer = None
    for p in doc.paragraphs:
        if "This publication has been carefully prepared" in p.text:
            disclaimer = p
            break
    assert disclaimer is not None
    # Both Technovage Solution mentions in the disclaimer are intact
    assert disclaimer.text.count("Technovage Solution") == 2


def test_render_preview_html_embeds_template_images_as_data_uris():
    """The preview must embed the DMC template's images (logo, cover
    background, etc.) as base64 data URIs so the sandboxed iframe can
    render them without external requests. Stripping images would
    visibly break the cover page."""
    from app.services.reporting.render import render_preview_html
    html = render_preview_html(_make_ctx())
    # Image tags with data: URIs from the template
    data_uri_imgs = re.findall(
        r'<img src="data:image/(?:png|jpeg);base64,[A-Za-z0-9+/=]+"',
        html,
    )
    # The DMC template has 8 images; the cover page is the dominant
    # user-visible one. We don't require all 8 (some may be dropped by
    # mammoth if unreferenced) but at least the logo + cover background
    # must be present.
    assert len(data_uri_imgs) >= 2, (
        f"expected >=2 data: URI images, got {len(data_uri_imgs)}"
    )
    # Total payload must be large enough to actually carry the images
    # (a stripped preview is ~30-40KB; with the 1.4MB cover image
    # embedded the preview is well over 100KB).
    assert len(html.encode("utf-8")) >= 100_000, (
        f"preview payload too small ({len(html)} chars) — images were stripped"
    )


def test_render_preview_html_cover_table_is_first_table_in_body():
    """The DMC template's title page is the first <table> in the docx
    body. The preview must preserve that ordering so the cover page
    (with the logo + client name) renders above the scope and findings
    sections."""
    from app.services.reporting.render import render_preview_html
    html = render_preview_html(_make_ctx())
    body_match = re.search(r"<body[^>]*>(.*)</body>", html, re.DOTALL)
    assert body_match is not None
    body = body_match.group(1)
    first_table = re.search(r"<table.*?</table>", body, re.DOTALL)
    assert first_table is not None
    # The first table must contain the cover-page labels ("For:", "Type:",
    # "From:", "Date:") and the client name + start date.
    first = first_table.group(0)
    assert "For" in first
    assert "Type" in first
    assert "From" in first
    assert "Date" in first
    assert "Acme Corp" in first
